apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
  namespace: dotnetapp
spec:
  provider: azure
  secretObjects:
    - secretName: azure-kv-secret
      type: Opaque
      data:
        - objectName: ExternalService--ApiKey
          key: ExternalService--ApiKey
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 98239fcf-5120-4130-ad1c-5d58c8e19971
    keyvaultName: devopsdemothanya
    tenantId: 9d0ebc8a-6260-4b50-88a4-0f52ed6a7e8a
    objects: |
      array:
        - |
          objectName: ExternalService--ApiKey
          objectType: secret
