apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
  namespace: dotnetapp
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"                # Don't use pod identity
    clientID: "${SP_APP_ID}"               # Environment variable
    clientSecret: "${SP_PASSWORD}"         # Environment variable
    tenantId: "${AZURE_TENANT_ID}"         # Environment variable
    keyvaultName: devopsdemothanya
    objects: |
      array:
        - |
          objectName: dbpassword
          objectType: secret
