name: CD - Auto Deploy to AKS

on:
  push:
    branches:
      - main
      - nonroot

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS Context
      run: |
        az aks get-credentials \
          --resource-group ${{ secrets.AKS_RG }} \
          --name ${{ secrets.AKS_NAME }} \
          --overwrite-existing

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/secretproviderclass.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
        kubectl apply -f k8s/monitoring-ingress.yaml
